// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJpAPtqPcWGAHUf8tSzygZHrjLT7_Ysfo',
    appId: '1:371992176663:web:91bc1c668ff5be38849452',
    messagingSenderId: '371992176663',
    projectId: 'finance-tracker-app-b8f95',
    authDomain: 'finance-tracker-app-b8f95.firebaseapp.com',
    storageBucket: 'finance-tracker-app-b8f95.firebasestorage.app',
    measurementId: 'G-359L1ES9P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSYXbRytzE1aywZ04Oa3FjmUSTS8zqiZQ',
    appId: '1:371992176663:android:576051220bf21ef1849452',
    messagingSenderId: '371992176663',
    projectId: 'finance-tracker-app-b8f95',
    storageBucket: 'finance-tracker-app-b8f95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnsHP57DHZ14yTe2_2sLpDpEPeigmKMu8',
    appId: '1:371992176663:ios:839f7ab05481405e849452',
    messagingSenderId: '371992176663',
    projectId: 'finance-tracker-app-b8f95',
    storageBucket: 'finance-tracker-app-b8f95.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnsHP57DHZ14yTe2_2sLpDpEPeigmKMu8',
    appId: '1:371992176663:ios:839f7ab05481405e849452',
    messagingSenderId: '371992176663',
    projectId: 'finance-tracker-app-b8f95',
    storageBucket: 'finance-tracker-app-b8f95.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJpAPtqPcWGAHUf8tSzygZHrjLT7_Ysfo',
    appId: '1:371992176663:web:56d6d3affa3db177849452',
    messagingSenderId: '371992176663',
    projectId: 'finance-tracker-app-b8f95',
    authDomain: 'finance-tracker-app-b8f95.firebaseapp.com',
    storageBucket: 'finance-tracker-app-b8f95.firebasestorage.app',
    measurementId: 'G-DG2T4M1MRM',
  );
}
